"""HTML report renderer.

Uses Jinja2 to produce a standalone HTML file from a
:class:`~aisec.core.models.ScanReport`.  When external template files are
not found the renderer falls back to a minimal inline template.
"""

from __future__ import annotations

import logging
from dataclasses import asdict
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any
from uuid import UUID

from jinja2 import Environment, FileSystemLoader, BaseLoader, TemplateNotFound

from aisec.core.models import ScanReport

logger = logging.getLogger(__name__)

# Default template directory (sibling ``templates/`` package)
_DEFAULT_TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "templates"


# ---------------------------------------------------------------------------
# Jinja2 helpers
# ---------------------------------------------------------------------------

def _make_serializable(obj: Any) -> Any:
    """Convert domain types so Jinja2 can iterate and display them."""
    if isinstance(obj, UUID):
        return str(obj)
    if isinstance(obj, datetime):
        return obj.isoformat()
    if isinstance(obj, Enum):
        return obj.value
    if isinstance(obj, dict):
        return {str(k): _make_serializable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_make_serializable(item) for item in obj]
    return obj


def _build_context(report: ScanReport) -> dict[str, Any]:
    """Build the template context dictionary from a ScanReport."""
    data = asdict(report)
    return _make_serializable(data)


# ---------------------------------------------------------------------------
# Minimal fallback template
# ---------------------------------------------------------------------------

_FALLBACK_TEMPLATE = """\
<!DOCTYPE html>
<html lang="{{ language }}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AiSec Report</title>
<style>
  body { font-family: system-ui, sans-serif; background: #1a1a2e; color: #e0e0e0; margin: 0; padding: 2rem; }
  h1, h2, h3 { color: #00d4ff; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th, td { border: 1px solid #333; padding: 0.5rem 0.75rem; text-align: left; }
  th { background: #0f3460; }
  .badge { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 4px; font-weight: bold; font-size: 0.85rem; }
  .critical { background: #dc3545; color: #fff; }
  .high { background: #fd7e14; color: #fff; }
  .medium { background: #ffc107; color: #000; }
  .low { background: #28a745; color: #fff; }
  .info { background: #17a2b8; color: #fff; }
  .card { background: #16213e; border: 1px solid #0f3460; border-radius: 8px; padding: 1.25rem; margin: 1rem 0; }
  footer { margin-top: 3rem; text-align: center; color: #666; font-size: 0.85rem; }
</style>
</head>
<body>
<h1>AiSec Security Analysis Report</h1>
<p>Target: <strong>{{ target_name }}</strong> | Image: <code>{{ target_image }}</code></p>
<p>Generated: {{ generated_at }} | Duration: {{ scan_duration_seconds }}s | Version: {{ aisec_version }}</p>

<h2>Executive Summary</h2>
<div class="card">
  <p>Overall Risk: <span class="badge {{ executive_summary.overall_risk_level }}">{{ executive_summary.overall_risk_level | upper }}</span></p>
  <p>Total Findings: {{ executive_summary.total_findings }}</p>
  <p>{{ executive_summary.summary_text }}</p>
</div>

<h2>Risk Overview</h2>
<div class="card">
  <p>AI Risk Score: {{ risk_overview.ai_risk_score }}/100</p>
  <p>Attack Surface: {{ risk_overview.attack_surface_score }}/100</p>
  <p>Data Exposure: {{ risk_overview.data_exposure_score }}/100</p>
  <p>Agency Risk: {{ risk_overview.agency_risk_score }}/100</p>
  <p>Supply Chain: {{ risk_overview.supply_chain_score }}/100</p>
  <p>Compliance: {{ risk_overview.compliance_score }}/100</p>
</div>

<h2>Findings</h2>
{% for finding in all_findings %}
<div class="card">
  <h3>{{ finding.title }} <span class="badge {{ finding.severity }}">{{ finding.severity | upper }}</span></h3>
  <p>{{ finding.description }}</p>
  {% if finding.remediation %}<p><strong>Remediation:</strong> {{ finding.remediation }}</p>{% endif %}
</div>
{% endfor %}

<footer>Generated by AiSec v{{ aisec_version }}</footer>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def render(
    report: ScanReport,
    output_path: Path,
    template_dir: Path | None = None,
) -> Path:
    """Render a scan report to a standalone HTML file.

    The renderer looks for a Jinja2 template named
    ``report_<language>.html.j2`` (e.g. ``report_en.html.j2``) inside
    *template_dir*.  If the template is not found, a minimal built-in
    fallback template is used instead.

    Args:
        report: The complete scan report.
        output_path: Destination file path.
        template_dir: Directory containing Jinja2 templates.  Defaults to
            the ``templates/`` directory shipped with this package.

    Returns:
        The resolved path to the written HTML file.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    template_dir = Path(template_dir) if template_dir else _DEFAULT_TEMPLATE_DIR
    template_name = f"report_{report.language}.html.j2"
    context = _build_context(report)

    try:
        env = Environment(
            loader=FileSystemLoader(str(template_dir)),
            autoescape=True,
        )
        template = env.get_template(template_name)
        logger.info("Using template %s from %s", template_name, template_dir)
    except (TemplateNotFound, OSError):
        logger.warning(
            "Template %s not found in %s; using fallback template",
            template_name,
            template_dir,
        )
        env = Environment(loader=BaseLoader(), autoescape=True)
        template = env.from_string(_FALLBACK_TEMPLATE)

    html = template.render(**context)

    output_path.write_text(html, encoding="utf-8")
    return output_path.resolve()
